force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Public</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Value__c</fullName>
    <label>Total Value</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red Bull Racing</fullName>
            </value>
            <value>
                <fullName>Mercedes-AMG Petronas Formula One Team</fullName>
            </value>
            <value>
                <fullName>Scuderia Ferrari</fullName>
            </value>
            <value>
                <fullName>McLaren F1 Team</fullName>
            </value>
            <value>
                <fullName>Alpine F1 Team</fullName>
            </value>
            <value>
                <fullName>Aston Martin Cognizant Formula One Team</fullName>
            </value>
            <value>
                <fullName>Scuderia AlphaTauri</fullName>
            </value>
            <value>
                <fullName>Alfa Romeo Racing Orlen</fullName>
            </value>
            <value>
                <fullName>Haas F1 Team</fullName>
            </value>
            <value>
                <fullName>Williams Racing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Sponsorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sponsorship__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Sponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DriverControllerTest.cls
@isTest
public class DriverControllerTest {
    @isTest
    static void testGetActiveDrivers() {
  
        Account sponsor = new Account(
            Name = 'Test Sponsor',
            Sector__c = 'Private',
            Industry = 'Agriculture',
            Total_Value__c = 10000000
        );
        insert sponsor;


        Contact driver = new Contact(
            FirstName = 'John',
            LastName = 'Doe',
            Email = 'john.doe@example.com',
            Active__c = true,
            Team__c = 'Williams Racing' 
        );
        insert driver;


        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            AccountId = sponsor.Id,
            StageName = 'Closed Won',
            CloseDate = Date.today(),
            Amount = 10000
        );
        insert opp;

        Sponsorship__c sponsorship1 = new Sponsorship__c(
            Sponsor__c = sponsor.Id,
            Opportunity__c = opp.Id,
            Driver__c = driver.Id,
            Value__c = 5000,
            Active__c = true
        );
        insert sponsorship1;

        Test.startTest();
        List<Map<String, Object>> drivers = DriverController.getActiveDrivers();
        Test.stopTest();

        System.assertEquals(1, drivers.size(), 'Must return 1 active drivers.');
    }
}