force-app/main/default/objects/Contact/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red Bull Racing</fullName>
            </value>
            <value>
                <fullName>Mercedes-AMG Petronas Formula One Team</fullName>
            </value>
            <value>
                <fullName>Scuderia Ferrari</fullName>
            </value>
            <value>
                <fullName>McLaren F1 Team</fullName>
            </value>
            <value>
                <fullName>Alpine F1 Team</fullName>
            </value>
            <value>
                <fullName>Aston Martin Cognizant Formula One Team</fullName>
            </value>
            <value>
                <fullName>Scuderia AlphaTauri</fullName>
            </value>
            <value>
                <fullName>Alfa Romeo Racing Orlen</fullName>
            </value>
            <value>
                <fullName>Haas F1 Team</fullName>
            </value>
            <value>
                <fullName>Williams Racing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Sponsorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sponsorship__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Sponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DriverController.cls
public with sharing class DriverController {
    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getActiveDrivers() {
        List<Contact> contacts = [
            SELECT Id, Name, Team__c
            FROM Contact
            WHERE Active__c = true
        ];
        Map<Id, Contact> contactMap = new Map<Id, Contact>(contacts);
        
        List<Sponsorship__c> sponsorships = [
            SELECT Driver__c,  Value__c, Sponsor__r.Name
            FROM Sponsorship__c
            WHERE Driver__c IN :contactMap.keySet()
        ];
      

        Map<Id, String> mainSponsorMap = new Map<Id, String>();
        Map<Id, Decimal> mainAmountMap = new Map<Id, Decimal>();
        for (Sponsorship__c sponsorship : sponsorships) {
            Id contactId = sponsorship.Driver__c;
            String sponsorName = sponsorship.Sponsor__r.Name;
            Decimal amount = sponsorship.Value__c;
          
            if (!mainAmountMap.containsKey(contactId) || amount > mainAmountMap.get(contactId)) {
                mainAmountMap.put(contactId, amount);
                mainSponsorMap.put(contactId, sponsorName);
            }
        }


        List<Map<String, Object>> drivers = new List<Map<String, Object>>();
        String imageUrl = '/resource/User'; 

        for (Contact contact : contacts) {
            Map<String, Object> driver = new Map<String, Object>();
            driver.put('Id', contact.Id);
            driver.put('Name', contact.Name);
            driver.put('Team', contact.Team__c);
            driver.put('MainSponsor', mainSponsorMap.get(contact.Id));
            driver.put('ImageUrl', imageUrl); 
            drivers.add(driver);
        }
        
        return drivers;
    }
}