force-app/main/default/objects/Sponsorship__c/Sponsorship__c.object-meta.xml
<CustomObject>
    <label>Sponsorship</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Sponsorship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sponsorships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sponsorship__c/fields/Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Sponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sponsorships</relationshipLabel>
    <relationshipName>Sponsorships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sponsorship__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/YearDeactivation.cls
public class YearDeactivation implements Schedulable {
    public void execute(SchedulableContext context) {
        List<Sponsorship__c> sponsorshipsToUpdate = [
            SELECT Id, Active__c, CreatedDate, Value__c, Sponsor__c
            FROM Sponsorship__c
            WHERE Active__c = TRUE AND CreatedDate <= :System.today().addYears(-1)
        ];
        for (Sponsorship__c sponsorship : sponsorshipsToUpdate) {
            sponsorship.Active__c = false;
        }

        if (!sponsorshipsToUpdate.isEmpty()) {
            update sponsorshipsToUpdate;
        }

    }
}